# Generated by Django 3.1.1 on 2021-03-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=150)),
                ('organizador', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=13)),
                ('emai', models.EmailField(max_length=254)),
                ('meta', models.IntegerField(default=100000)),
                ('costo', models.IntegerField(default=10000)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
            ],
        ),
    ]
