# Generated by Django 3.1.1 on 2021-03-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='emai',
            new_name='email',
        ),
    ]
