# Generated by Django 3.1.1 on 2021-03-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210311_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
