# Generated by Django 3.1.1 on 2021-03-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20210312_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=20),
        ),
    ]
